name: Chrome Setup and Test

on:
  push:
  # デバッグ用に手動実行を許可
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"

env:
  TZ: Asia/Tokyo
  LANG: ja_JP.UTF-8

jobs:
  setup-chrome:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        id: setup-chrome
        with:
          chrome-version: "131"

      - name: Chrome のバージョンとパスを確認
        run: |
          echo "インストールされたChromeのパス: ${{ steps.setup-chrome.outputs.chrome-path }}"
          ${{ steps.setup-chrome.outputs.chrome-path }} --version
